// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/location.proto

package location

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Location service

func NewLocationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Location service

type LocationService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Location_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Location_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Location_BidiStreamService, error)
}

type locationService struct {
	c    client.Client
	name string
}

func NewLocationService(name string, c client.Client) LocationService {
	return &locationService{
		c:    c,
		name: name,
	}
}

func (c *locationService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Location.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationService) ClientStream(ctx context.Context, opts ...client.CallOption) (Location_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Location.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &locationServiceClientStream{stream}, nil
}

type Location_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type locationServiceClientStream struct {
	stream client.Stream
}

func (x *locationServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *locationServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *locationServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *locationService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Location_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Location.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &locationServiceServerStream{stream}, nil
}

type Location_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type locationServiceServerStream struct {
	stream client.Stream
}

func (x *locationServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *locationServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *locationServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *locationService) BidiStream(ctx context.Context, opts ...client.CallOption) (Location_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Location.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &locationServiceBidiStream{stream}, nil
}

type Location_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type locationServiceBidiStream struct {
	stream client.Stream
}

func (x *locationServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *locationServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *locationServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *locationServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Location service

type LocationHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Location_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Location_ServerStreamStream) error
	BidiStream(context.Context, Location_BidiStreamStream) error
}

func RegisterLocationHandler(s server.Server, hdlr LocationHandler, opts ...server.HandlerOption) error {
	type location interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Location struct {
		location
	}
	h := &locationHandler{hdlr}
	return s.Handle(s.NewHandler(&Location{h}, opts...))
}

type locationHandler struct {
	LocationHandler
}

func (h *locationHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.LocationHandler.Call(ctx, in, out)
}

func (h *locationHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.LocationHandler.ClientStream(ctx, &locationClientStreamStream{stream})
}

type Location_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type locationClientStreamStream struct {
	stream server.Stream
}

func (x *locationClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *locationClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *locationHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LocationHandler.ServerStream(ctx, m, &locationServerStreamStream{stream})
}

type Location_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type locationServerStreamStream struct {
	stream server.Stream
}

func (x *locationServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *locationServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *locationHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.LocationHandler.BidiStream(ctx, &locationBidiStreamStream{stream})
}

type Location_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type locationBidiStreamStream struct {
	stream server.Stream
}

func (x *locationBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *locationBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *locationBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *locationBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *locationBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *locationBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
