---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        securityContext:
          allowPrivilegeEscalation: false
        image: user:latest
        envFrom:
        - configMapRef:
            name: user-env
